---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-f9fb4a8a5cc1> in <module>
      2 ### YOUR CODE HERE ###
      3 #v1
----> 4 hdr = exp.submit(config=hyperdrive_config)
      5 RunDetails(hdr).show()
      6 #/v1

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_jupyter_common/__init__.py in submit(self, config, tags, **kwargs)
     84 def _experiment_submit_notebook_decorator(original_submit):
     85     def submit(self, config, tags=None, **kwargs):
---> 86         run = original_submit(self, config, tags, **kwargs)
     87         _update_run_created_from(run)
     88         return run

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/experiment.py in submit(self, config, tags, **kwargs)
    217         submit_func = get_experiment_submit(config)
    218         with self._log_context("submit config {}".format(config.__class__.__name__)):
--> 219             run = submit_func(config, self.workspace, self.name, **kwargs)
    220         if tags is not None:
    221             run.set_tags(tags)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/hyperdrive/_search.py in search(hyperdrive_config, workspace, experiment_name, **kwargs)
     93     compute_target = None
     94     if hyperdrive_config.estimator is not None:
---> 95         compute_target = hyperdrive_config.estimator._compute_target
     96     if hyperdrive_config.run_config is not None:
     97         compute_target = ComputeTarget(workspace=workspace, name=hyperdrive_config.run_config.run_config.target)

AttributeError: 'ScriptRunConfig' object has no attribute '_compute_target'
